import type { Metadata } from "next";
import { IBM_Plex_Mono, Manrope, Architects_Daughter } from "next/font/google";
import "./globals.css";

const display = IBM_Plex_Mono({
  variable: "--font-display",
  subsets: ['latin'],
  weight: ["100", '200', '300', '400', '500', '600', '700'],
});

const body = Manrope({
  variable: "--font-body",
  subsets: ["latin"],
});

const handwritten = Architects_Daughter({
  variable: "--font-handwritten",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "28:01 | estrella",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${display.variable} ${body.variable} ${handwritten.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

